### ISSUE TITLE
Issue with using GPU on a campus cluster

### ISSUE THREAD

**Issue by rahimr2** [abTEM/abTEM#174]
Hello, 

I have been trying to use abTEM on a campus cluster and would like to utilise the GPU, but have been running into a 'CUDA is a stub library' error. This could be a problem with the cluster itself but wanted to check here in case there is something I am doing wrong.

This is the error I encounter:

   

>  main(mp_ids, api_key,
>   File "/projects/eng/shared/pyhuang/Rahim/abtem_training_data/mass_simulate/training_from_abTEM_for_cluster.py", line 246, in main
>     intensity = electron_probe.build().compute()
>   File "/home/rahimr2/.conda/envs/abtem_2/lib/python3.9/site-packages/abtem/waves.py", line 1724, in build
>     return self._validate_and_build(scan=scan, max_batch=max_batch, lazy=lazy)
>   File "/home/rahimr2/.conda/envs/abtem_2/lib/python3.9/site-packages/abtem/waves.py", line 1691, in _validate_and_build
>     probes = self._lazy_build_waves(probe, max_batch)
>   File "/home/rahimr2/.conda/envs/abtem_2/lib/python3.9/site-packages/abtem/waves.py", line 1267, in _lazy_build_waves
>     meta=xp.array((), dtype=get_dtype(complex=True)),
>   File "/home/rahimr2/.conda/envs/abtem_2/lib/python3.9/site-packages/cupy/_creation/from_data.py", line 53, in array
>     return _core.array(obj, dtype, copy, order, subok, ndmin, blocking)
>   File "cupy/_core/core.pyx", line 2408, in cupy._core.core.array
>   File "cupy/_core/core.pyx", line 2435, in cupy._core.core.array
>   File "cupy/_core/core.pyx", line 2578, in cupy._core.core._array_default
>   File "cupy/_core/core.pyx", line 137, in cupy._core.core.ndarray.__new__
>   File "cupy/_core/core.pyx", line 225, in cupy._core.core._ndarray_base._init
>   File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
>   File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
>   File "cupy/cuda/memory.pyx", line 1444, in cupy.cuda.memory.MemoryPool.malloc
>   File "cupy/cuda/device.pyx", line 40, in cupy.cuda.device.get_device_id
>   File "cupy_backends/cuda/api/runtime.pyx", line 202, in cupy_backends.cuda.api.runtime.getDevice
>   File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
> cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorStubLibrary: CUDA driver is a stub library
> srun: error: ccc0312: task 0: Exited with exit code 1

I did test running cupy in a separate script on cluster:

```
import cupy as cp

print(cp.cuda.runtime.runtimeGetVersion())


if cp.is_available():
    device = cp.cuda.Device()
    print("Device ID:", device.id)
    print("Device name:", cp.cuda.runtime.getDeviceProperties(device.id)['name'])

else:
    print("CUDA is not available")
```

and it worked as expected. Is this error something that seems to be on the end of abTEM, or my specific cluster?

Thank you!!!!

**Comment by rahimr2** [comment]
My apologies, the issue was that I was not importing cupy first. Importing cupy, then abtem has fixed the issue.

**Comment by TomaSusi** [comment]
No worries, glad you got it working – and maybe this issue will help someone else in the future!
